// lib/game/path_level.dart
import 'dart:math';

/// FlowForge: draw ONE unbroken path from start to end that visits every
/// cell exactly once (a Hamiltonian path on a grid). Generated by carving a
/// real space-filling snake path through the grid via randomized DFS that
/// always covers all cells — so a solution is guaranteed to exist.
class PathLevel {
  final int index;
  final int size;
  final String difficulty;
  final int start;
  final int end;
  final List<int> solutionPath; // full guaranteed path start..end
  PathLevel({
    required this.index,
    required this.size,
    required this.difficulty,
    required this.start,
    required this.end,
    required this.solutionPath,
  });
}

class LevelGenerator {
  static PathLevel generate(int levelIndex) {
    int size;
    String difficulty;
    if (levelIndex < 50) {
      size = 4;
      difficulty = 'Easy';
    } else if (levelIndex < 100) {
      size = 5;
      difficulty = 'Medium';
    } else {
      size = 6;
      difficulty = 'Hard';
    }

    final rng = Random(levelIndex * 7649 + levelIndex * 41 + 17);
    final path = _hamiltonian(size, rng);
    return PathLevel(
      index: levelIndex,
      size: size,
      difficulty: difficulty,
      start: path.first,
      end: path.last,
      solutionPath: path,
    );
  }

  /// Randomized DFS that backtracks until it finds a path covering every cell.
  static List<int> _hamiltonian(int s, Random rng) {
    final total = s * s;
    for (int attempt = 0; attempt < 200; attempt++) {
      final start = rng.nextInt(total);
      final path = <int>[start];
      final visited = List<bool>.filled(total, false);
      visited[start] = true;
      if (_dfs(s, start, visited, path, total, rng)) {
        return path;
      }
    }
    // guaranteed-coverage fallback: boustrophedon (snake) path
    final snake = <int>[];
    for (int r = 0; r < s; r++) {
      if (r.isEven) {
        for (int c = 0; c < s; c++) snake.add(r * s + c);
      } else {
        for (int c = s - 1; c >= 0; c--) snake.add(r * s + c);
      }
    }
    return snake;
  }

  static bool _dfs(int s, int cur, List<bool> visited, List<int> path,
      int total, Random rng) {
    if (path.length == total) return true;
    final r = cur ~/ s, c = cur % s;
    final dirs = [
      [-1, 0],
      [1, 0],
      [0, -1],
      [0, 1]
    ]..shuffle(rng);
    for (final d in dirs) {
      final nr = r + d[0], nc = c + d[1];
      if (nr < 0 || nc < 0 || nr >= s || nc >= s) continue;
      final ni = nr * s + nc;
      if (visited[ni]) continue;
      visited[ni] = true;
      path.add(ni);
      if (_dfs(s, ni, visited, path, total, rng)) return true;
      path.removeLast();
      visited[ni] = false;
    }
    return false;
  }
}
